Demo1/Models/NHANVIEN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.CHAMCONGs = new HashSet<CHAMCONG>();
            this.CHUCVUs = new HashSet<CHUCVU>();
            this.HOCVANKINHNGHIEMs = new HashSet<HOCVANKINHNGHIEM>();
            this.HOPDONGLAODONGs = new HashSet<HOPDONGLAODONG>();
            this.LUONGs = new HashSet<LUONG>();
            this.QUANLYNGHIPHEPs = new HashSet<QUANLYNGHIPHEP>();
            this.TANGCAs = new HashSet<TANGCA>();
        }
    
        public string MSNV { get; set; }
        public string HOTEN { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string HINHANH { get; set; }
        public string QUEQUAN { get; set; }
        public string TAMTRU { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string DANTOC { get; set; }
        public string HOCVAN { get; set; }
        public Nullable<System.DateTime> NGAYVAOLAM { get; set; }
        public string CCCD { get; set; }
        public string MSHD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAMCONG> CHAMCONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUCVU> CHUCVUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOCVANKINHNGHIEM> HOCVANKINHNGHIEMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONGLAODONG> HOPDONGLAODONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUONG> LUONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUANLYNGHIPHEP> QUANLYNGHIPHEPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TANGCA> TANGCAs { get; set; }
    }
}

Demo1/Controllers/NhanVienController.cs
using Demo1.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo1.Controllers
{
    public class NhanVienController : Controller
    {
        // GET: NhanVien
        QLNVCTYEntities6 db = new QLNVCTYEntities6();
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 6;
            // Lấy danh sách nhân viên
            return View(db.NHANVIENs.ToList().OrderBy(n => n.MSNV).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Create()
        {
            // Tạo danh sách cho việc chọn giới tính
            ViewBag.GioiTinhList = new List<SelectListItem>
{
    new SelectListItem { Text = "Nam", Value = "Nam" },
    new SelectListItem { Text = "Nữ", Value = "Nữ" },
    new SelectListItem { Text = "Không xác định", Value = "Không xác định" }
};

            return View();
        }

        // POST: Tạo mới nhân viên
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NHANVIEN nhanvien, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                // Kiểm tra xem file đã được upload chưa
                if (file != null && file.ContentLength > 0)
                {
                    // Lưu hình ảnh vào database
                    using (var reader = new BinaryReader(file.InputStream))
                    {
                        byte[] imageData = reader.ReadBytes(file.ContentLength);
                        nhanvien.HINHANH = Convert.ToBase64String(imageData);
                    }
                }

                // Lưu thông tin nhân viên vào database
                db.NHANVIENs.Add(nhanvien);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            // Nếu dữ liệu không hợp lệ, quay lại trang tạo mới và hiển thị lỗi
            ViewBag.GioiTinhList = new List<SelectListItem>
{
    new SelectListItem { Text = "Nam", Value = "Nam" },
    new SelectListItem { Text = "Nữ", Value = "Nữ" },
    new SelectListItem { Text = "Không xác định", Value = "Không xác định" }
};

            return View(nhanvien);
        }
        public ActionResult Delete(string id)
        {
            var nhanVien = db.NHANVIENs.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }

            return View(nhanVien); // Trả về view ConfirmDelete với thông tin nhân viên để xác nhận xóa
        }

        public ActionResult TinhtongNV()
        {
            int tongSoLuongNV = db.NHANVIENs.Count();
            ViewBag.TongSoLuongNV = tongSoLuongNV;

            return View();
        }
    }
}

Demo1/Views/NhanVien/Create.cshtml
@model Demo1.Models.NHANVIEN

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin1.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "NhanVien", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>NHANVIEN</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MSNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MSNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MSNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HOTEN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HOTEN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HOTEN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GIOITINH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.GIOITINH, (IEnumerable<SelectListItem>)ViewBag.GioiTinhList, "Chọn giới tính", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GIOITINH, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- NGAYSINH -->
        <div class="form-group">
            @Html.LabelFor(model => model.NGAYSINH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" name="NGAYSINH" id="NGAYSINH" class="form-control" />
                @Html.ValidationMessageFor(model => model.NGAYSINH, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- HINHANH -->
        <div class="form-group">
            @Html.LabelFor(model => model.HINHANH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control" />
                @Html.ValidationMessageFor(model => model.HINHANH, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.QUEQUAN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QUEQUAN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QUEQUAN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TAMTRU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TAMTRU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TAMTRU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DANTOC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DANTOC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DANTOC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HOCVAN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HOCVAN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HOCVAN, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- NGAYVAOLAM -->
        <div class="form-group">
            @Html.LabelFor(model => model.NGAYVAOLAM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" name="NGAYVAOLAM" id="NGAYVAOLAM" class="form-control" />
                @Html.ValidationMessageFor(model => model.NGAYVAOLAM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CCCD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CCCD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CCCD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MSHD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MSHD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MSHD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Demo1/Views/NhanVien/Delete.cshtml
@model Demo1.Models.NHANVIEN

@{
    ViewBag.Title = "Xác nhận xóa nhân viên";
    Layout = "~/Views/Shared/_LayoutAdmin1.cshtml";
}

<h2>Xác nhận xóa nhân viên</h2>

<p>Bạn có chắc chắn muốn xóa nhân viên "<strong>@Model.HOTEN</strong>" không?</p>

<form action="@Url.Action("Delete", "NhanVien", new { id = Model.MSNV })" method="post">
    @Html.AntiForgeryToken()
    <input type="submit" value="Xóa" class="btn btn-danger" />
    <a href="@Url.Action("Index", "NhanVien")" class="btn btn-default">Hủy bỏ</a>
</form>

Demo1/Views/NhanVien/Index.cshtml
@model IEnumerable<Demo1.Models.NHANVIEN>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin1.cshtml";
}

<h2 style="text-align:center; color:red">Danh Sách Nhân Viên</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Họ Tên
        </th>
        <th>
           Giới Tính
        </th>
        <th>
            Ngày Sinh
        </th>
        <th>
            Hình Ảnh
        </th>
        <th>
            Quên Quán
        </th>
        <th>
            Tạm Trú
        </th>
        <th>
            SĐT
        </th>
        <th>
           Email
        </th>
        <th>
           Dân Tộc
        </th>
        <th>
            Học Vấn
        </th>
        <th>
           Ngày Vào Làm
        </th>
        <th>
            Số căn cước công dân
        </th>
        <th>
            Mã số hợp đồng
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.HOTEN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GIOITINH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NGAYSINH)
        </td>
        <td>
            <img src="@Url.Content("~/img/" + item.HINHANH)" alt="Hình ảnh nhân viên" width="130" height="110" />
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.QUEQUAN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TAMTRU)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SDT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EMAIL)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DANTOC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HOCVAN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NGAYVAOLAM)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CCCD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MSHD)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.MSNV }) |
            @Html.ActionLink("Details", "Details", new { id = item.MSNV }) |
 
            @Html.ActionLink("Xóa", "Delete", new { id = item.MSNV }, new { @class = "btn btn-danger" })
    

        </td>
    </tr>
}

</table>

Demo1/Views/NhanVien/TinhtongNV.cshtml
@{
    ViewBag.Title = "TinhtongNV";
    Layout = null;
}




<p style="color:red; font-weight:bold">Tổng số lượng nhân viên<br />(hiện có): @ViewBag.TongSoLuongNV</p>